### ISSUE TITLE
[FEATURE] Non-nord version of the theme

### ISSUE THREAD

**Issue by vyvir** [alvatip/Nordzy-icon#158]
**Is your feature request related to a problem? Please describe.**
I like this icon theme, and I like that it does not try to copy another brand. However, I don't like the nord color scheme that it uses. The icons feel desaturated enough that I find it difficult to look at them and distinguish them from each other.

**Describe the solution you'd like**
Make an alternative version that uses a fully saturated color scheme, just like a lot of other icon themes do (WhiteSur, PlagueSur, etc.)

**Describe alternatives you've considered**
I tried using WhiteSur with regular icons, but I don't like the design choices that they used, particularly with their inspiration from a certain phone brand). I used PlagueSur for quite some time, but I like the stylistic choices in Nordzy more.

**Comment by alvatip** [comment]
Hi @asdhio-github 
Sorry for the delay of the answer, I was busy on another project :stuck_out_tongue: 
i will see what I can do to convert all colors to non nord and create a non nord version of the theme. 
However, it might take some time :stuck_out_tongue:

**Comment by Vibhav201** [comment]
I don't know much about icon themes, but I think it would be really difficult to achieve this. But, I agree that the Nord scheme is too mild and limited for icon colours. 
It's awesome that you are considering this. I'll be waiting as well. You're awesome bro.

**Comment by alvatip** [comment]
Hi @asdhio-github, @Vibhav201, 
So here is what I did, because there is too much variability within icons (mainly appliction icons) I cannot create a script that will update the colors during installation of the theme (it might miss some, some icons are not nice following the color conversion, some needs minor adaptation, ...) 

However I made a copy of Nordzy-icons and batch converted as best as possible all the icons
It can be found [here](https://github.com/alvatip/Nordzy-plain)

Consider it in **beta** as there is still many modification to make and colors to modify to make it better,
Any comments are welcome :wink: however please open them in the new theme, I will try to improve it as fast as possible but I cannot promise anything :stuck_out_tongue:

**Comment by alvatip** [comment]
Update: After giving it some taught, I think that the best option could be to create a script and include an option in the installer to convert all the colors
I will have a look to the current state as this might require some update of several icons but final result and update will be easier

**Comment by alvatip** [comment]
Progress for this is in a separate branch: https://github.com/alvatip/Nordzy-icon/tree/158-feature-non-nord-version-of-the-theme

Current status: Addition of an argument "-v" or "--variant" -- result is good, however some icons needs to be updated in their Nord version to work properly with the script. Also currently the default name of the theme is not updated to indicate that colors are non nord, will update that later during the week
